#baseUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
dev_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
sit_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
uat_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
# dev_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
# sit_url=https://playwright.dev/java/
# uat_url=https://www.selenium.dev/
browser=chromium
retryCount=2
defaultWait=10
