name: .NET Playwright SpecFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-report:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Install Playwright Browsers
        run: |
          $script = Get-ChildItem -Path bin/Release -Recurse -Filter playwright.ps1 | Select-Object -First 1
          pwsh -File $script.FullName install
        shell: pwsh
      - name: Test
        run: dotnet test --no-build --configuration Release --filter "Category=regression"
      - name: Install LivingDoc CLI
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
      - name: Add dotnet tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
      - name: Generate LivingDoc
        run: livingdoc test-assembly bin/Release/net8.0/Playwright_NUnit_Csharp_BDD.dll
      - name: Upload LivingDoc report
        uses: actions/upload-artifact@v4
        with:
          name: LivingDoc
          path: LivingDoc.html
